{
    "name": "Avior Tax API Integration",
    "version": "16.0.0.0.2",
    "author": "Collins Lagat",
    "description": "Compute Sales Tax in the United States using the Avior Tax API",
    "license": "LGPL-3",
    "category": "Accounting",
    "website": "https://collinslagat.com",
    "depends": ["account", "sale", "base_geolocalize"],
    "data": [
        "security/ir.model.access.csv",
        "data/aviortax_data.xml",
        "wizard/aviortax_configuration_login_view.xml",
        "views/aviortax_view.xml",
        "views/partner_view.xml",
        "views/account_move_action.xml",
        "views/account_move_view.xml",
        "views/account_tax_view.xml",
        "views/account_fiscal_position_view.xml",
    ],
    "installable": True,
    "application": True,
}
